const EVENT_SAMPLE = {
  "exporter_label": "exporter.host (10.20.30.40)",
  "sgt_name": "SGT Name",
  "sgt_id": "SGT ID",
  "device_name": "Core NetFlow Collector",
  "exporter_hostname": "exporter.host",
  "target_host_group_paths": "Vendors (Outside Hosts), Outside",
  "start_active_time_local": "2020-05-28T00:07:02 (Z)",
  "source_url": "https://192.168.100.99/some/path",
  "interface_index": "4",
  "device_id": "201",
  "target_ip": "199.237.198.232",
  "source_device_type": "Windows",
  "source_mac_address": "00:0c:29:be:35:5a",
  "alarm_category_name": "Anomaly",
  "target_mac_address_vendor": "XEROX",
  "target_hostname": "www.lancope.com",
  "source_hostname": "source.host",
  "time_local": "2020-05-28T00:07:02 (Z)",
  "alarm_id": "3Y-13Y1-QJJ2-YYA9-U",
  "domain_id": "101",
  "alarm_type_id": "52",
  "alarm_severity_id": "5",
  "exporter_ip": "10.20.30.40",
  "host_group_relationship_map_name": "Test Map Name",
  "target_url": "https://192.168.100.99/some/path",
  "target_host_group_ids": "45, 0",
  "target_device_type": "Windows",
  "alarm_severity_name": "Critical",
  "alarm_type_description": "The source host has downloaded an unusual amount of data from one or more hosts.",
  "alarm_note": "admin @ 2020-05-28T00:07:02 (Z)\nSample alarm note text.",
  "domain_name": "Corporate Domain",
  "target_username": "admin",
  "alarm_category_id": "0",
  "source_zone_path": "HR Department (Inside Hosts -> HQ)",
  "end_active_time_local": "2020-05-28T00:07:02 (Z)",
  "device_type_id": "swa",
  "sgt_peer_name": "SGT Peer Name",
  "target_host_group_names": "Vendors, Outside",
  "host_group_relationship_name": "Test Relationship Name",
  "translated_source_ip": "3.3.3.3",
  "device_type_name": "FlowCollector",
  "end_active_time": "2020-05-28T00:07:02Z",
  "target_zone_name": "Vendors",
  "port": "80",
  "source_host_group_names": "HR Department, Inside",
  "translated_source_port": "3000",
  "host_group_relationship_id": "1813",
  "alarm_status": "ACTIVE",
  "device_ip": "10.0.28.131",
  "source_country_code": "XR",
  "alarm_type_name": "Suspect Data Hoarding",
  "start_active_time": "2020-05-28T00:07:02Z",
  "smc_ip": "192.168.100.9",
  "source_zone_name": "HR Department",
  "spi": "4",
  "source_label": "source.host (192.168.200.9)",
  "device_hostname": "device.host",
  "details": "Observed 57.88M bytes. Policy maximum allows up to 20M bytes.",
  "source_username": "admin",
  "target_zone_id": "24",
  "source_zone_id": "23",
  "target_country_code": "US",
  "source_ip": "192.168.200.9",
  "time": "2020-05-28T00:07:02Z",
  "source_country_name": "RFC 1918",
  "host_group_relationship_map_id": "1814",
  "translated_destination_port": "4000",
  "source_host_group_paths": "HR Department (Inside Hosts -> HQ), Inside",
  "source_host_port": "1234",
  "target_label": "www.lancope.com(199.237.198.232)",
  "source_mac_address_vendor": "XEROX",
  "sgt_peer_id": "SGT Peer ID",
  "target_zone_path": "Vendors (Outside Hosts)",
  "translated_destination_ip": "4.4.4.4",
  "source_host_group_ids": "23,1",
  "protocol": "6",
  "host_group_relationship_description": "Test Relationship Description",
  "target_country_name": "United States",
  "target_mac_address": "00:0c:29:be:35:5a"
}

module.exports = EVENT_SAMPLE
